snowtricks/src/Snowtricks/CoreBundle/Entity/Picture.php
<?php
/**
 * Created by PhpStorm.
 * User: Davis
 * Date: 01/04/2017
 * Time: 16:52
 */

namespace Snowtricks\CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Snowtricks\CoreBundle\Entity\User;
use Symfony\Component\Form\Exception\InvalidArgumentException;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 *
 * @ORM\Table(name="snow_picture")
 * @ORM\Entity(repositoryClass="Snowtricks\CoreBundle\Repository\PictureRepository")
 * @ORM\HasLifecycleCallbacks()
 *
 * @UniqueEntity(fields={"address"}, message="Erreur interne, cette image existe déjà, merci de re-essayer plus tard.")
 */
class Picture {
    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     */
    private $id = 0;
    /**
     * @ORM\Column(name="address", type="string", nullable=false)
     *
     */
    private $address = "";
    /**
     * @ORM\Column(name="created_at", type="datetime")
     *
     */
    private $createdAt;
    /**
     * @ORM\ManyToOne(targetEntity="Snowtricks\CoreBundle\Entity\User")
     * @ORM\JoinColumn(nullable=true)
     *
     */
    private $createdBy = NULL;

    /**
     * @ORM\ManyToOne(targetEntity="Snowtricks\CoreBundle\Entity\Trick", inversedBy="pictures")
     *
     */
    private $trick;

    private $file;

    private $cropData = NULL;

    private $cropedPicture;

    private $originalWidth;

    private $originalHeight;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }
    /**=================================================================================================================
    =                                                                                                                 =
    =                                          Getters                                                                =
    =                                                                                                                 =
    ================================================================================================================**/
    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return \User
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * @return mixed
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @return mixed
     */
    public function getTrick()
    {
        return $this->trick;
    }

    /**
     * @return mixed
     */
    public function getCropData()
    {
        return $this->cropData;
    }

    /**
     * @return mixed
     */
    public function getFullSize()
    {
        return $this->getUploadDir().'/fullSize/'.$this->address;
    }

    /**
     * @return mixed
     */
    public function getThumbnailSize()
    {
        return $this->getUploadDir().'/thumbnail/'.$this->address;
    }
    /**=================================================================================================================
    =                                                                                                                 =
    =                                          Setters                                                                =
    =                                                                                                                 =
    ================================================================================================================**/
    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @param string $address
     */
    public function setAddress($address)
    {
        $this->address = $address;
    }

    /**
     * @param \DateTime $created_at
     */
    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @param \User $created_by
     */
    public function setCreatedBy(User $createdBy)
    {
        $this->createdBy = $createdBy;
    }

    /**
     * @param mixed $file
     */
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;
        $this->upload();

    }

    /**
     * @param mixed $Trick
     */
    public function setTrick($Trick)
    {
        $this->trick = $Trick;
    }

    /**
     * @param mixed $cropData
     */
    public function setCropData($cropData)
    {
        $this->cropData = $cropData;
    }
    /**=================================================================================================================
    =                                                                                                                 =
    =                                           Others                                                                =
    =                                                                                                                 =
    ================================================================================================================**/


    private function upload()
    {
        // If there is no file, we do nothing
        if (null === $this->file) {
            return;
        }
        if ($this->file->getMimeType() != 'image/jpg' && $this->file->getMimeType() != 'image/jpeg'){
            throw new InvalidArgumentException('Le fichier doit être de type image jpg.');
        }

        // we get the orgiginal name of the file
        $name = $this->file->getClientOriginalName();
        $ext = substr(strrchr($name,'.'),1);
        $newName = uniqid(rand(), true).'.'.$ext;
        $this->address = $newName;

        $this->file->move($this->getUploadRootDir().'/tmp', $newName);

        // We clean file attribute (witch is now useless)
        $this->file = NULL;

    }

    public function getUploadDir()
    {
        return 'uploads';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    /**
     * @ORM\PostRemove
     */
    public function removePicture()
    {
        unlink($this->getUploadRootDir().'/../'.$this->getFullSize());
        unlink($this->getUploadRootDir().'/../'.$this->getThumbnailSize());
    }

    public function crop(){
        if ($originalPictureSize = getimagesize($this->getUploadRootDir().'/tmp/'.$this->address)){
            $cropData = $this->getCropData();

            $this->originalWidth = $originalPictureSize[0];
            $this->originalHeight = $originalPictureSize[1];

            if ($this->originalWidth > 1170){
                $newHeight = $this->originalHeight / $this->originalWidth * 1170;
                $this->createThumbnail(1170, $newHeight, 'tmp', 'tmp');
                $this->originalHeight = $newHeight;
                $this->originalWidth = 1170;
            }

            $finalWidth = $this->originalWidth * ($cropData->getCropSizeWidth()/$cropData->getCropHolderWidth());
            $finalHeight = $this->originalHeight * ($cropData->getCropSizeHeight()/$cropData->getCropHolderHeight());

            $sourcePointY = $this->originalHeight * $cropData->getCropPositionTop() / ($cropData->getCropSizeHeight()+$cropData->getCropPositionTop());
            $sourcePointX = $this->originalWidth * $cropData->getCropPositionLeft() / ($cropData->getCropSizeWidth()+$cropData->getCropPositionLeft());

            $originalPicture = imagecreatefromjpeg($this->getUploadRootDir().'/tmp/'.$this->address);

            $this->cropedPicture = imagecreatetruecolor($finalWidth, $finalHeight);

            imagecopyresampled($this->cropedPicture, $originalPicture,
                0, 0,
                $sourcePointX, $sourcePointY,
                $finalWidth, $finalHeight,
                $finalWidth, $finalHeight
            );

            imagejpeg($this->cropedPicture, $this->getFullSize(), 100);
            imagedestroy($this->cropedPicture);
            imagedestroy($originalPicture);
            unlink($this->getUploadRootDir().'/tmp/'.$this->address);
            $this->cropedPicture = NULL;
        }

        return $this;
    }

    public function createThumbnail($finalWidth, $finalHeight, $destination = 'thumbnail', $origin = 'fullSize'){
        if ($originalPictureSize = getimagesize($this->getUploadRootDir().'/../'.$this->getUploadDir().'/'.$origin.'/'.$this->address)){

            $originalPicture = imagecreatefromjpeg($this->getUploadRootDir().'/../'.$this->getUploadDir().'/'.$origin.'/'.$this->address);
            $originalPictureSize = getimagesize($this->getUploadRootDir().'/../'.$this->getUploadDir().'/'.$origin.'/'.$this->address);

            $this->cropedPicture = imagecreatetruecolor($finalWidth, $finalHeight);
            imagecopyresampled($this->cropedPicture, $originalPicture,
                0, 0,
                0, 0,
                $finalWidth, $finalHeight,
                $originalPictureSize[0], $originalPictureSize[1]);

            imagejpeg($this->cropedPicture, $this->getUploadRootDir().'/../'.$this->getUploadDir().'/'.$destination.'/'.$this->address, 100);
            imagedestroy($this->cropedPicture);
            imagedestroy($originalPicture);
            $this->cropedPicture = NULL;
        }

        return $this;
    }

}

snowtricks/src/Snowtricks/CoreBundle/Controller/DefaultController.php
<?php

namespace Snowtricks\CoreBundle\Controller;

use Snowtricks\CoreBundle\Entity\Trick;
use Snowtricks\CoreBundle\Form\Model\TrickSearch;
use Snowtricks\CoreBundle\Form\Type\TrickForm;
use Snowtricks\CoreBundle\Form\Type\TrickSearchForm;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\CssSelector\Exception\InternalErrorException;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    public function indexAction(Request $request)
    {
        $repository = $this->getDoctrine()->getManager()->getRepository('SnowtricksCoreBundle:Trick');
        $form = $this->createForm(TrickSearchForm::class);
        $search = new TrickSearch(); // creating an empty TrickSearch (width defaults values)

        // if new search form receved
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $search = $form->getData();
        }

        $tricks = $repository->getTricks($search);

        return $this->render('SnowtricksCoreBundle:Default:index.html.twig', array(
            'tricks' => $tricks,
            'form' => $form->createView(),
            'search' => $search,
        ));
    }

    public function figureAction(Request $request,Trick $trick){

        if ($trick === NULL){
            throw $this->createNotFoundException('Il semblerait que la figure que vous recherchez n\'existe pas...');
        }

        return $this->render('SnowtricksCoreBundle:Default:figure.html.twig', array(
            'trick' => $trick,
            'request' => $request
        ));
    }

    public function addAction(Request $request){

        $form = $this->createForm(TrickForm::class);

        $form->handleRequest($request);
        if ($id = $this->formHandler($form, false)){
            return $this->redirectToRoute('SnowtricksCore_Figure', array(
                'id' => $id
            ));
        }

        return $this->render('SnowtricksCoreBundle:Default:addTrick.html.twig', array(
            'form' => $form->createView(),
            'title' => 'Création d\'une figure'
        ));

    }

    public function updateAction(Request $request, Trick $trick){

        $form = $this->createForm(TrickForm::class, $trick);

        $form->handleRequest($request);
        if ($this->formHandler($form, true)){
            return $this->redirectToRoute('SnowtricksCore_Trick_Update', array(
                'id' => $trick->getId()
            ));
        }


        return $this->render('SnowtricksCoreBundle:Default:addTrick.html.twig', array(
            'form' => $form->createView(),
            'title' => 'Modification d\'une figure',
            'trick' => $trick
        ));
    }

    public function deleteAction(Trick $trick){
        $em = $this->getDoctrine()->getManager();

        $em->remove($trick);
        $em->flush();

        $this->addFlash('success', 'La figure à été supprimée.');

        return $this->redirectToRoute('snowtricks_core_homepage');
    }

    private function formHandler($form, $isAnUpdate){
        $em = $this->getDoctrine()->getManager();
        if ($form->isSubmitted() && $form->isValid()){
            $trick = $form->getData();

            $trick->setCreatedBy(
                $this->getUser()
            );
            foreach ($trick->getVideos() as $video){
                $em->persist($video);
                if ($video->getCreatedBy() === NULL){
                    $video->setCreatedBy($this->getUser());
                    $video->setTrick($trick);
                }
            }
            foreach ($trick->getPictures() as $picture){

                if ($picture->getCreatedBy() === NULL){
                    $picture->setCreatedBy($this->getUser());
                    $picture->setTrick($trick);
                    $picture->crop()->createThumbnail(308, 173);
                }
                $em->persist($picture);
            }
            if ($isAnUpdate){
                $message = 'La figure à été mise à jour.';
            } else {
                $message = 'La figure à été ajouté, merci :)';
                $em->persist($trick);
            }
            try{
                $em->flush();
            } catch (Exception $e){
                throw new InternalErrorException("Une erreur est survenue lors de l'insertion en base donnée.");
            }
            $this->addFlash('success', $message);


            

            return $trick->getId();
        }
    }
}

snowtricks/src/Snowtricks/CoreBundle/Resources/views/Default/addTrick.html.twig
{% extends ":Default:layout.html.twig" %}

{% block title %}Ajouter une figure{% endblock %}

{% block content %}

    <div class="row bottom10">
        <div class="col-xs-12 text-center">
            <h2>{{ title }}</h2>
        </div>
        <div class="row">

            <div class="container">

                {% if title == 'Modification d\'une figure' %}
                    <div class="col-xs-12"><a href="{{ path('SnowtricksCore_Figure', {id: trick.id}) }}"><div class="col-xs-3 col-xs-offset-9 btn btn-success">Revenir à la figure</div></a></div>
                {% endif %}

                {{ form_start(form) }}
                <div class="col-xs-12 top10 bottom10">
                    {{ form_row(form.title) }}
                </div>
                <div class="col-xs-12 top10 bottom10">
                    {{ form_row(form.description) }}
                </div>

                <div class="col-xs-12 top10">
                    {{ form_row(form.group) }}
                </div>

                <div class=col-xs-12 id="pictures-form">
                    <div class="col-xs-12 text-center top10 bottom10"><strong>Ajouter une image à la figure :</strong>
                    <p>(image au format jpg de moins de 1 mo)</p></div>
                    <div class="col-xs-12 text-center bottom10">{{ form_row(form.uploadPictures) }}</div>
                    <div class="col-xs-10 col-xs-offset-1"><hr></div>
                    <div class="col-xs-12 top10" id="pictures-preview"></div>
                    {% if title == 'Modification d\'une figure' %}
                        <div class="col-xs-12 text-right" id="picture-content">
                            {{ render(controller(
                            'SnowtricksCoreBundle:Pictures:deleteMainPage',
                            { 'trick': trick,
                            }
                            )) }}
                        </div>
                    {% endif %}
                </div>

                <div class=col-xs-12 id="videos-form">
                    <div class="col-xs-11 text-justify">
                        <p id="add-video-help"><strong>Aide :</strong> Pour ajouter une video, vous devez vous rendre sur la page de la video en question, (youtube dailymotion ou autre)
                        chercher le lien de partage (option partager), puis copier <strong>l'embed code</strong> (option intégrer, iframe ou toutes données html fournies par le site pour intégrer
                            leur video), et enfin coller le texte dans le champ "Ajoutez une video à la figure" de ce formulaire.</p>
                    </div>
                    <div class="col-xs-1" id="about-add-video"><img src="https://openclipart.org/image/25px/svg_to_png/227978/Question-Mark-Icon.png&disposition=attachment" alt="Aide" /></div>
                    <div class="col-xs-12 text-center bottom10">{{ form_row(form.videos) }}</div>
                    <a href="#videos-form" id="add_video" class="btn btn-default">Ajouter une video</a>
                    <div class="col-xs-10 col-xs-offset-1"><hr></div>
                    <div class="col-xs-12 top10 bottom10" id="videos-preview"></div>
                    {% if title == 'Modification d\'une figure' %}
                        <div class="col-xs-12 text-right">
                            <div class="col-xs-12 text-right" id="video-content">
                                {{ render(controller(
                                'SnowtricksCoreBundle:Videos:deleteMainPage',
                                { 'trick': trick,
                                }
                                )) }}
                            </div>
                    {% endif %}
                </div>

                {{ form_end(form) }}

            </div>
        </div>

    </div>

{% endblock %}

snowtricks/src/Snowtricks/CoreBundle/Resources/views/Default/deleteAccount.html.twig
{% extends ":Default:layout.html.twig" %}

{% block title %}Modification de compte{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-xs-11">
                <p>Suite à la suppréssion de votre compte, personne n'aura plus accès à ce dernier. Seuls persisterons les messages que vous aurez pu poster.</p>
                <p>Nous sommes tristes de vous voir partir :( .</p>
                <p>A une prochaine fois peut être...</p>

            </div>
        </div>
    </div>

{% endblock %}

snowtricks/src/Snowtricks/CoreBundle/Resources/views/Default/index.html.twig
{% extends ":Default:layout.html.twig" %}

{% block title %}Accueil{% endblock %}

{% block content %}

            <!-- Texte de bienvenue
            ================================================== -->
            <div class="row">
                <div class="col-xs-12 text-center">
                    <h2>Bienvenue</h2>
                </div>
                <div class="col-xs-12 text-justify">

                    <p><strong>Bonjour à vous</strong> et bienvenue sur le site de Snowtricks. il est entièrement dédié aux amateurs de snowboard.</p>
                    <p> Vous trouverez au fils des pages de ce site, toute une liste de figures de snow, agrémentées de photos, de vidéos et de
                        précieux commentaires et conseils de nos trés chers uilisateurs, faisant parti de la communauté de Snowtricks. </p>
                    {% if is_granted('ROLE_USER') == false %}
                   <p><strong>N'hésitez pas à créer un compte</strong>, vous pourrez ainsi mieux profiter du contenu du site, en pouvant, par exemple créer vos propres figures,
                       ajouter ou modifer du contenu aux figures existantes, et poster vos propres messages afin d'échanger avec la communauté. </p>
                    <p>Alors, plus une seconde à perdre, inscrivez vous, et entrez dans la communauté Snowtricks.</p>
                    {% endif %}

                </div>
            </div>

            <!-- ================================================== -->
            <div class="row">
                <div class="col-xs-12 text-center">
                    <h3>Cherchez votre bonheur :</h3>
                    <p><strong>(et si il n'y est pas, créez le en vous inscrivant)</strong></p>
                </div>
            </div>

            <!-- Search Form
            ================================================== -->
            <div class="row">
                {{ form_start(form) }}

                    {{ form_row(form.firstResult) }}
                    <div class="col-xs-11 noPaddingRight top10">
                        {{ form_row(form.search) }}
                    </div>
                    <div class="col-xs-1 noPaddingLeft top10">
                        <span class="btn btn-info search-btn" id="search"><i class="fa fa-search"></i></span>
                    </div>

                    <div class="col-lg-2 col-xs-6 top10 text-center">
                        {{ form_row(form.number) }}
                    </div>
                    <div class="col-lg-3 col-lg-offset-2 col-xs-6 top10 text-center">
                        {{ form_row(form.orderedBy) }}
                    </div>
                    <div class="col-lg-3 col-lg-offset-1 col-xs-6 top10 text-center">
                        {{ form_row(form.order) }}
                    </div>
                    <div class="col-lg-1 col-xs-6 top10 text-center">
                        <button type="submit" class="btn btn-info sort-btn col-xs-12" id="sort" formnovalidate><i class="fa fa-sort"></i></button>
                    </div>

                {{ form_end(form) }}
            </div>
            <!-- ================================================== -->

            <!-- Tricks list
            ================================================== -->

            {% for trick in tricks %}
                {% set thumb = trick.pictures %}
                {% if thumb is empty %}
                    {% set thumbnail = 'bundles/snowtrickscore/img/no_picture.png' %}
                {% else %}
                    {% set picture = random(thumb) %}
                    {% set thumbnail = picture.thumbnailSize %}
                {% endif %}
                <div class="stick col-sm-4">
                    <a href="{{ path('SnowtricksCore_Figure', { 'id': trick.id}) }}">
                        <div class="trick-stick">
                            <div class="col-xs-12 text-center trick-stick-title"><h4>{{ trick.title }}</h4></div>
                            <div class="col-xs-12 stick-thumb"><img src="{{ asset(thumbnail) }}"></div>
                            <div class="col-xs-12 stic-links">
                            {% if is_granted('ROLE_USER') %}
                                <a href="{{ path('SnowtricksCore_Trick_Update', { 'id': trick.id}) }}" title="Modifier"><div class="col-xs-1 col-lg-offset-1 text-center"><h5><i class="fa fa-pencil" aria-hidden="true"></i></h5></div></a>
                                <div class="col-xs-8 text-center">{{ trick.group.name }}</div>
                                <a href="{{ path('SnowtricksCore_Trick_Delete', { 'id': trick.id}) }}" title="Supprimer"><div class="col-xs-1 text-center"><h5><i class="fa fa-trash-o" aria-hidden="true"></i></h5></div></a>
                            {% else %}
                                <div class="col-xs-offset-2 col-xs-8 text-center top10 bottom10">{{ trick.group.name }}</div>
                            {% endif %}
                            </div>
                            <div class="col-xs-12 text-justify top10 bottom10 trick-stick-desc">{{ trick.description }}</div>
                            <div class="col-xs-12 text-left"><strong>{{ trick.createdBy.name }} {{ trick.createdBy.surname }}</strong></div>
                        </div>
                    </a>
                </div>

            {% endfor %}

            <div class="col-xs-12 top10 bottom10">
                {% if search.firstResult != 0 %}
                <div class="col-xs-3">
                    <span class="btn btn-info prev-btn"><i class="fa fa-arrow-circle-left"></i> Précédent</span>
                </div>
                {% endif %}

                {% if search.firstResult == 0 %}
                    <div class="col-xs-4 col-xs-offset-4 text-center" id="pagination-conter">
                {% else %}
                    <div class="col-xs-4 col-xs-offset-1 text-center" id="pagination-conter">
                {% endif %}
                    {{ ((search.firstResult+1) // search.number)+1 }} sur {{ (tricks|length/search.number)|round(0, 'ceil') }}
                    </div>

                {% if search.firstResult + search.number < tricks|length %}
                     <div class="col-xs-3 col-sm-offset-1 next-btn">
                        <span class="btn btn-info">Suivant <i class="fa fa-arrow-circle-right"></i></span>
                     </div>
                {% endif %}
            </div>
            <!-- ================================================== -->
{% endblock %}

snowtricks/src/Snowtricks/CoreBundle/Resources/views/Default/messages.html.twig
{% block content %}

    <div class="col-xs-12">
        <div class="col-xs-12 text-left">
            {% if messages is not empty %}
                <h3>Fil de discussion :</h3>
            {% elseif is_granted('ROLE_USER') %}
                <h3>Pas encore de message</h3>
                <p>Ne soyez pas timide, allez y !!!</p>
            {% else %}
                <h3>Pas encore de message</h3>
                <p>Inscrivez vous pour poster le votre :)</p>
            {% endif %}
        </div>
        {% if is_granted('ROLE_USER') %}
            <div class="col-xs-10 col-xs-offset-1 noPadding" id="message-form">
                {{ form_start(form) }}
                <div class="col-xs-12">
                    {{ form_label(form.message) }}
                </div>
                <div class="col-xs-12">
                    {{ form_errors(form.message) }}
                </div>
                <div class="col-xs-10 noPadding">
                    {{ form_widget(form.message) }}
                </div>
                <div class="col-xs-2 noPadding">
                    {{ form_end(form) }}
                </div>
            </div>
            <div class="col-xs-12 text-center" id="moderate-form">

                {% if is_granted('ROLE_MODERATOR') %}
                    <div class="col-xs-10 col-xs-offset-1 noPadding" id="update-message-form">
                        {{ form_start(updateForm) }}
                        <div class="col-xs-12">
                            Quelle est la raison de cette modération ?
                        </div>
                        <div class="col-xs-12">
                            {{ form_errors(updateForm.message) }}
                        </div>
                        <div class="col-xs-10 noPadding">
                            {{ form_widget(updateForm.message) }}
                            {{ form_row(updateForm.id) }}
                        </div>
                        <div class="col-xs-2 noPadding">
                            {{ form_end(updateForm) }}
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endif %}
        {% for message in messages %}
            <div class="col-xs-10 col-xs-offset-1 message-container text-center">
                <div class="col-xs-4 col-sm-2 message-picture">

                    {%  if message.createdBy.picture.address == "" %}
                        {% set picture =  "/bundles/snowtricksuser/img/default-user.png" %}
                    {% else %}
                        {% set picture = message.createdBy.picture.thumbnailSize %}
                        {% set picture =  "/" ~ picture %}
                    {% endif %}
                    <img src="{{ picture }}" alt="{{ message.createdBy.name }} {{ message.createdBy.surname }}" />
                </div>
                <div class="col-xs-8 col-sm-10">
                    <div class="col-xs-10 col-sm-5 text-left msg-author"><strong>{{ message.createdBy.name }} {{ message.createdBy.surname }}</strong>
                    </div>
                    {% if is_granted('ROLE_MODERATOR') %}
                        <a href="#"><div class="col-xs-2 noPadding msg-moderate" id="{{ message.id }}"><i class="fa fa-trash-o fa-lg" aria-hidden="true"></i></div></a>
                    {% endif %}
                    <div class="col-xs-12 col-sm-5 text-right msg-date">Le : {{ message.createdAt|date('d/m/Y à: H:i:s') }}</div>
                </div>

                    <div class="col-xs-12 text-justify message-text" id="message-text-{{ message.id }}">{{ message.message }}</div>

            </div>
        {% endfor %}
        <div class="col-xs-10 col-xs-offset-1 bottom10">

            <div class="col-xs-2 text-left">
                {% if search.firstResult != 0 %}
                    <div class="btn btn-info" id="msg-prev-btn"><i class="fa fa-arrow-circle-left"></i> Précédent</div>
                {% endif %}
            </div>

            <div class="col-xs-8">
                {{ form_start(searchForm) }}
                {{ form_row(searchForm.firstResult) }}
                {{ form_row(searchForm.number) }}
                {{ form_end(searchForm) }}
            </div>

                <div class="col-xs-2 text-right">
                    {% if search.firstResult + search.number < messages|length %}
                        <div class="btn btn-info" id="msg-next-btn">Suivant <i class="fa fa-arrow-circle-right"></i></div>
                    {%  endif %}
                </div>

        </div>
    </div>

{% endblock %}

snowtricks/src/Snowtricks/CoreBundle/Resources/views/Default/pictures.html.twig
{% block content %}


    <div class="row bottom10">
        <div class="col-xs-12 text-center">
            {% if trick.pictures is empty %}
                <p>Aucune photo n'est encore liée à cette figure.</p>
            {% else %}
            <p>Voici les photos déjà liées à la figure "<a class="strong-link" href="{{ path('SnowtricksCore_Figure', { 'id': trick.id }) }}">{{ trick.title }}</a>" </p>
            <p>Cliquez sur supprimer pour les effacer définitivement.</p>
            {% endif %}
        </div>
        {% for picture in trick.pictures %}
            <div class="col-sm-2 text-center top10 bottom10">
                <div class="col-xs-12"><img src="{{ asset(picture.thumbnailSize) }}" /></div>
                <div class="btn btn-warning del-picture" data-url="{{ path('SnowtricksCore_Pictures_Delete_One', {idPicture: picture.id, idTrick: trick.id}) }}">Supprimer</div>
            </div>
        {% endfor %}
    </div>

{% endblock %}